name: deploy
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.AZURE_PREFIX }}acr
          resourceGroup: ${{ vars.AZURE_RG }}
          containerAppName: ${{ vars.AZURE_PREFIX }}containerapp
          containerAppEnvironment: ${{ vars.AZURE_PREFIX }}containerappenvironment